### ISSUE TITLE
Unable to upload Folder types

### ISSUE THREAD

**Issue by ccaum** [wizedkyle/sumologic-go-sdk#13]
I have an exported JSON file that I was hoping to import. Unmarshalling it to a types.Folder is easy enough, but I cannot use cip.BeginFolderAsyncImport() to import the content because that function expects a types.FolderSyncDefinition type and that type does not have all of the fields needed to import an exported JSON file.

Actually, I'm not sure a Folder type would work anyway since Folder.Children is of type []Content. Folders can contain folders, dashboards, and saved searches which the Content type doesn't support.

Can you think of any way to use this SDK to upload a folder object containing all of the possible children?

**Comment by wizedkyle** [comment]
@ccaum I don't believe there is a way in the current version of the SDK however, I have been pondering on this for a bit and I think it is possible just might require some interesting code to make it work plus a lot of trial and error.

I am currently working on a subset of the Sumo Logic CSE API for some upcoming projects, once I have gotten through that (hopefully before Christmas) I will come back around to this and see if I can pull something together.

**Comment by ccaum** [comment]
Thanks! I ended up copying your APIClient into my project and building my own upload function based on types that I've made for my CLI. It works beautifully. I would have called out directly to your APIClient, but I needed to call private functions so that wouldn't have worked.

**Comment by ccaum** [comment]
I'll go ahead and close this out. We can circle back later.
